kind: pipeline
name: "create git tag and deploy to Sandbox"
type: docker
steps:
- name: git-tag
  image: docker:git
  environment:
    gittoken:
      from_secret: token
  commands:
  - git remote set-url origin https://$${gittoken}@github.com/anshu2185/MuleCICDDemo.git
  - git tag -a dev-5.0.2 -m "created new dev tag"
  - git push --tags
  when:
      event: push
      branch: [development]


#- name: Unit Test
 # image: maven:3.6-jdk-8-alpine
  #commands:
  #- mvn clean test -s .maven/settings.xml
- name: Deploy to Sandbox
  image: maven:3.6-jdk-8-alpine
  environment:
    anypoint_userName:
      from_secret: username
    anypoint_passwrd:
      from_secret: password
  commands:
  - mvn clean package deploy -DmuleDeploy -DskipTests -Dmule.version=4.4.0 -Dusername=$${anypoint_userName} -Dpassword=$${anypoint_passwrd} -Denvironment=Sandbox -Dcloudhub.application.name=democicdanshu
  when:
   ref:
   - "refs/tags/dev*"

---
kind: pipeline
name: "Production Environment"
type: docker
trigger:
  ref:
    - "refs/tags/prod*"
steps:
#- name: Unit Test
 # image: maven:3.6-jdk-8-alpine
  #commands:
  #- mvn clean test -s .maven/settings.xml
- name: Deploy to Production
  image: maven:3.6-jdk-8-alpine
  environment:
    anypoint_userName:
      from_secret: username
    anypoint_passwrd:
      from_secret: password
  commands:
  - mvn clean package deploy -DmuleDeploy -DskipTests -Dmule.version=4.4.0 -Dusername=$${anypoint_userName} -Dpassword=$${anypoint_passwrd} -Denvironment=Sandbox -Dcloudhub.application.name=democicdanshu
  
  
