kind: pipeline
name: default
type: docker
steps:
- name: git-tag
  image: docker:git
  environment:
    gittoken:
      from_secret: token
  commands:
  - git remote set-url origin https://$${gittoken}@github.com/anshu2185/MuleCICDDemo.git
  - git tag -a dev-5.0.1 -m "created new dev tag"
  - git push --tags
when:
      event: push
      branch: [development]

---
kind: pipeline
name: "Sandbox Environment"
type: docker
trigger:
  ref:
    - "refs/tags/dev*"
steps:
#- name: Unit Test
 # image: maven:3.6-jdk-8-alpine
  #commands:
  #- mvn clean test -s .maven/settings.xml
- name: Deploy to Sandbox
  image: maven:3.6-jdk-8-alpine
  environment:
    anypoint_userName:
      from_secret: username
    anypoint_passwrd:
      from_secret: password
  commands:
  - mvn clean package deploy -DmuleDeploy -DskipTests -Dmule.version=4.4.0 -Dusername=$${anypoint_userName} -Dpassword=$${anypoint_passwrd} -Denvironment=Sandbox -Dcloudhub.application.name=democicdanshu
  
---
kind: pipeline
name: "Production Environment"
type: docker
trigger:
  ref:
    - "refs/tags/prod*"
steps:
#- name: Unit Test
 # image: maven:3.6-jdk-8-alpine
  #commands:
  #- mvn clean test -s .maven/settings.xml
- name: Deploy to Production
  image: maven:3.6-jdk-8-alpine
  environment:
    anypoint_userName:
      from_secret: username
    anypoint_passwrd:
      from_secret: password
  commands:
  - mvn clean package deploy -DmuleDeploy -DskipTests -Dmule.version=4.4.0 -Dusername=$${anypoint_userName} -Dpassword=$${anypoint_passwrd} -Denvironment=Sandbox -Dcloudhub.application.name=democicdanshu
  
  
