name: Delete Merged Branches

on:
  workflow_dispatch:
  
jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      

      - name: Get merged branches
        id: merged_branches
        run: |
          merged_branches=$(git branch --remote --merged | grep -vE "(sandbox|main)" | awk '{print $1}')
          echo $merged_branches >> $GITHUB_ENV

      - name: Delete branches
        run: |
          merged_branches=(${{ steps.merged_branches.outputs.branches }})

          for branch in "${merged_branches[@]}"; do
            if [[ $branch != "sandbox" && $branch != "main" ]]; then
              git push origin --delete $branch
              echo "Deleted branch: $branch"
            else
              echo "Skipped deletion of branch: $branch"
            fi
          done
