name: Delete Merged Branches

on:
  workflow_dispatch:
  
jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      

      - name: Get merged branches
        id: merged_branches
        run: |
          git fetch origin
          git checkout sandbox
          merged_branches=$(git branch -r --merged | grep -vE "(sandbox|main)" | sed 's/origin\///' | awk '{$1=$1};1')
          echo "BRANCHES=$merged_branches" >> $GITHUB_ENV
      - name: Print environment variables
        run: |
         env
      - name: Delete branches
        run: |
          merged_branches="${{ env.BRANCHES }}"

          for branch in $merged_branches; do
            if [[ $branch != "sandbox" && $branch != "main" ]]; then
              last_commit_date=$(git log -1 --format=%cd --date=iso "$branch")
              echo "commit: $last_commit_date"
              git push origin --delete $branch
              echo "Deleted branch: $branch"
            else
              echo "Skipped deletion of branch: $branch"
            fi
          done
